name: Firebase UI Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'

jobs:
  test:
    name: Run UI Tests on Firebase Test Lab
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Create local.properties with secrets
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        echo "TEST_ASSISTANT_ID=${{ secrets.TEST_ASSISTANT_ID }}" >> local.properties
      
    - name: Run lint
      run: ./gradlew lint
      
    - name: Build Debug APK and Test APK
      run: |
        ./gradlew :example:assembleDebug
        ./gradlew :widget:assembleDebugAndroidTest
      
    - name: 'Authenticate Cloud SDK'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.TEST_UI_GCLOUD_SERVICE_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Run UI Tests on Firebase Test Lab
      id: ui_tests
      continue-on-error: true
      run: |
        gcloud firebase test android run \
          --type instrumentation \
          --app example/build/outputs/apk/debug/example-debug.apk \
          --test widget/build/outputs/apk/androidTest/debug/widget-debug-androidTest.apk \
          --device model=akita,version=34,locale=en,orientation=portrait \
          --timeout 30m
        echo "ui_status=success" >> $GITHUB_OUTPUT

    - name: Check Test Results
      if: always()
      run: |
        if [[ "${{ steps.ui_tests.outcome }}" == "success" ]]; then
          echo "UI tests passed"
          exit 0
        else
          echo "UI tests failed"
          exit 1
        fi
        
    - name: Upload lint results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lint-results
        path: '**/build/reports/lint-results*.html'
        
    - name: Upload debug APKs
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: debug-apks
        path: |
          example/build/outputs/apk/debug/
          widget/build/outputs/apk/androidTest/debug/